name: Test & Lint

on:
  push:
    branches: [ "*" ]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn lint:formatting
      - run: yarn lint:eslint
